server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mymodel?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    servlet:
      multipart:
        max-file-size: 2MB
        max-request-size: 5MB
    global-config:
      db-config:
        logic-delete-field: delFlag
        logic-delete-value: 1
        logic-not-delete-value: 0
        id-type: auto
  #邮箱基本配置
  mail:
    #配置smtp服务主机地址
    # qq邮箱为smtp.qq.com          端口号465或587
    # sina    smtp.sina.cn
    # aliyun  smtp.aliyun.com
    # 163     smtp.163.com       端口号465或994
    host: smtp.qq.com
    #发送者邮箱
    username: 2390545586@qq.com
    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    password: xudognhodmcodhhg
    #端口号465或587
    port: 587
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          #超时时间
          timeout: 10000
          connectiontimeout: 10000
          writetimeout: 10000
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest