
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_financial?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    servlet:
      multipart:
        max-file-size: 2MB
        max-request-size: 5MB
    global-config:
      db-config:
        logic-delete-field: delFlag
        logic-delete-value: 1
        logic-not-delete-value: 0
        id-type: auto
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
server:
  port: 8080